language: java
jdk: openjdk11

- matrix:
  	includes:
		- env: FOLDER=labone
		- env: FOLDER=labtwo	
	
  
# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

install:
  - cd $FOLDER
  - java pro_wrapper.java version

script:
  - ./pro/bin/pro version
  - ./pro/bin/pro
