language: java
jdk: openjdk11


matrix:
  include:
    - env: FOLDER=labone PRO_SPECIAL_BUILD=''
    - env: FOLDER=labtwo PRO_SPECIAL_BUILD='early-access'
    - env: FOLDER=labthree PRO_SPECIAL_BUILD='early-access'
    - env: FOLDER=labfour PRO_SPECIAL_BUILD='early-access-loom'
    - env: FOLDER=labfive PRO_SPECIAL_BUILD='early-access'
  
# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

install:	
  - cd $FOLDER
  - java pro_wrapper.java version

script:
  - ./pro/bin/pro version
  - ./pro/bin/pro
